# Generated by Django 3.2.4 on 2021-06-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.CharField(max_length=50, null=True)),
                ('aDate', models.DateField(default=None)),
                ('cash', models.FloatField(blank=True, default=0, null=True)),
                ('equipment', models.FloatField(blank=True, default=0, null=True)),
                ('supplies', models.FloatField(blank=True, default=0, null=True)),
                ('accReciev', models.FloatField(blank=True, default=0, null=True)),
                ('notePay', models.FloatField(blank=True, default=0, null=True)),
                ('accPay', models.FloatField(blank=True, default=0, null=True)),
                ('OwnCapital', models.FloatField(blank=True, default=0, null=True)),
                ('revenew', models.FloatField(blank=True, default=0, null=True)),
                ('drawing', models.FloatField(blank=True, default=0, null=True)),
                ('expense', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
